### ISSUE TITLE
Should we remove unnecessary parts?

### ISSUE THREAD

**Issue by trinhpham** [appium/appium-docker-android#108]
Hello folks,

Correct me if I am wrong, but I think this image can be used as base image for many other implementations with multiple purposes. IMO, people can easily inherit this image then adding their needed parts, right? :)

Therefore, adding much additional tools makes the image size bigger (you know, the bigger size, the longer time for the deployment) than expected. As a DevOps developer, I feel good if the docker image size can be as small as possible. It's also less headache to DevSecOps guys if the image has less *additional purposes*. How's about you?

I see that there're some parts of this image are not necessary for an official image like this, such as:
- AppiumTestDistribution
- Android platform (I don't know if Appium use it or not, but it is fixed at version 25)
- Android build tool (I don't know if Appium use it or not)
- `zip`, `wget`, `salt-minion`, `xvfb`, etc package

Another (not much related) question is: Appium runs under NodeJS, why don't we just let this image base on the `node:lts` image?

Thanks

**Comment by budtmo** [comment]
Hi @trinhpham , 

The initial goal of this project is actually to support Appium users who use it to run UI-Test on real devices. For that purpose, we put any tool which make users easier to use and maintain it (sample case: if you use other project like [Docker-Android](https://github.com/budtmo/docker-android) and want to maintain the version of Appium without always pulling the newest image, you can use through salt). Docker-Android supports testing on real devices as well but for bigger purpose, e.g. running chaos testing, etc.

The other package like Android platform, because it is required for user who use selendroid as Automation framework as far as I remember. And we didnt use node image, because we had issue on installing some other tools (I dont remember which one).

In my opinion, the only thing that make the image big is installing Android platform, and I am not sure if someone still use selendroid. 

@SrinivasanTarget could you also give your opinion?

Feel free to send a PR to remove any part that are not needed anymore / reduce the size of the image.

**Comment by budtmo** [comment]
close due to no response. please feel free to reopen the ticket.
