### ISSUE TITLE
use the adb from anther container

### ISSUE THREAD

**Issue by ktoya** [appium/appium-docker-android#90]
The appium is running in container-appium 
docker run --privileged -d -p 4723:4723 -v /dev/bus/usb:/dev/bus/usb --name container-appium appium/appium

I understand it will start an adb server in the container,
however is it possible to use the adb outside of this container for example use the adb server running in the  physic machine(ubuntu 18.04)?

**Comment by butomo1989** [comment]
yes, it is possible by using adb connect, but you need to forward needed ports of adb from the container to outside. 
the other solution will be to share the volume between container and host so you dont need to have adb outside the container. 

I will close this issue for now because it is not an issue, please feel free to reopen it if needed.
